import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Manrope } from "next/font/google";
import { Inter } from "next/font/google";
import { Open_Sans } from "next/font/google";
import { Inria_Serif } from "next/font/google";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";

/* ---------------- Fonts ---------------- */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-inter",
});

const inriaSerif = Inria_Serif({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-inria-serif",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-manrope",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-openSans",
});

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-instrument-sans",
});

/* ---------------- Metadata ---------------- */

export const metadata: Metadata = {
  title: "Mastervance",
  description: "Generated by Mastervance team",

  // ✅ VERY IMPORTANT FOR MOBILE RESPONSIVENESS
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
};

/* ---------------- Root Layout ---------------- */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${manrope.variable}
          ${inter.variable}
          ${openSans.variable}
          ${inriaSerif.variable}
          ${instrumentSans.variable}
          antialiased
          overflow-x-hidden
        `}
      >
        {children}
      </body>
    </html>
  );
}
